fixtures:
  forge_modules:
    stdlib:       'puppetlabs/stdlib'
    powershell:   'puppetlabs/powershell'
    registry:     'puppetlabs/registry'
  repositories:
      facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
      puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      provision: 'https://github.com/puppetlabs/provision.git'
      opv:
        repo: "https://github.com/sheenaajay/opv.git"
        branch: "testingissue3"
  symlinks:
    chocolatey: "#{source_dir}"
