---
.gitattributes:
  # As this is for Windows, ERB files can be either LF or CRLF
  exclude:
  - "*.erb"

.gitignore:
  required:
    - ---.project

.gitlab-ci.yml:
  unmanaged: true

.travis.yml:
  unmanaged: true

.rubocop.yml:
  default_configs:
    inherit_from: .rubocop_todo.yml
    require:
    - rubocop-rspec

appveyor.yml:
  use_litmus: true
  matrix_extras:
    -
      RUBY_VERSION: 25-x64
      ACCEPTANCE: 'yes'
      TARGET_HOST: localhost
    -
      RUBY_VERSION: 25-x64
      ACCEPTANCE: 'yes'
      TARGET_HOST: localhost
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

Gemfile:
  use_litmus: true
  required:
    ':system_tests':
      - gem: 'nokogiri'
        platforms:
          - ruby
          - mswin
          - mingw
          - x64_mingw
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"

spec/default_facts.yml:
  unmanaged: true

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
